In [7]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
url="https://books.toscrape.com/catalogue/category/books_1/index.html"

In [4]:

response=requests.get(url)

In [5]:
response.status_code

200

In [8]:
# Parse the HTML content
soup=BeautifulSoup(response.content)

In [9]:
#Find the side_categories section
side_categories=soup.find("div",class_="side_categories")

In [11]:
#select the links inside the nested <ul>
categories = side_categories.find("ul").find_all("li")

In [12]:
for li in categories:
    print(li.a.get_text(strip=True))

Books
Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime

In [14]:
category_links=side_categories.select("ul ul li a")
for link in category_links:
     print(link.get_text(strip=True))

Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime

In [25]:
travel_link = None

for link in side_categories.find_all("a"):
    if link.get_text(strip=True) == "Travel":
        travel_link = link
        break

In [26]:
print(travel_link)

<a href="../books/travel_2/index.html">

                                Travel

                        </a>

In [27]:
travel_href = travel_link.get("href")

print(travel_href)

../books/travel_2/index.html

In [28]:
#Then convert it to the actual URL
from urllib.parse import urljoin

travel_url = urljoin(url, travel_href)

print(travel_url)

https://books.toscrape.com/catalogue/category/books/travel_2/index.html

In [29]:
response = requests.get(travel_url)

travel_soup = BeautifulSoup(response.text, "html.parser")

In [30]:
#Find all the individual books
books = travel_soup.find_all("article", class_="product_pod")

In [31]:
print(len(books))

11

In [32]:
print(books[0])

<article class="product_pod">
<div class="image_container">
<a href="../../../its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="../../../../media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="../../../its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
<div class="product_price">
<p class="price_color">Â£45.17</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [34]:
#Extract the title
title=books[0].h3.a.get("title")
print(title)

It's Only the Himalayas

In [35]:
#. Extract the price
price=books[0].find(
    "p",
    class_="price_color"
).get_text(strip=True)
print(price)

Â£45.17

In [37]:
#Extract availability
availability=books[0].find(
    "p",
    class_="instock availability"
).get_text(strip=True)
print(availability)

In stock

In [38]:
#put it into a loop
books_data = []
for book in books:
    title=book.h3.a.get("title")
    price = book.find(
        "p",
        class_="price_color"
    ).get_text(strip=True)

    availability = book.find(
        "p",
        class_="instock availability"
    ).get_text(strip=True)
    
    books_data.append({
        "Title": title,
        "Price": price,
        "Availability": availability
    })

In [39]:
travel_books_df = pd.DataFrame(books_data)

In [40]:
travel_books_df.head()

                                               Title    Price Availability
0                            It's Only the Himalayas  Â£45.17     In stock
1  Full Moon over Noahâs Ark: An Odyssey to Mou...  Â£49.43     In stock
2  See America: A Celebration of Our National Par...  Â£48.87     In stock
3  Vagabonding: An Uncommon Guide to the Art of L...  Â£36.94     In stock
4                               Under the Tuscan Sun  Â£37.33     In stock

In [41]:
"""
scrape all books in each category and save it in a data frame:
Finds every book category.
Gets each category's URL.
Visits each category page.
Scrapes every book on that page.
Follows the Next button to get additional pages.
Stores everything in one pandas DataFrame.
"""

"\nscrape all books in each category and save it in a data frame:\nFinds every book category.\nGets each category's URL.\nVisits each category page.\nScrapes every book on that page.\nFollows the Next button to get additional pages.\nStores everything in one pandas DataFrame.\n"

In [43]:
#find the category <a> tags
outer_ul = side_categories.find("ul")
category_list = outer_ul.find("ul")
category_links=category_list.find_all("a")

In [45]:
for link in category_links:
    print(link.get_text(strip=True), link.get("href"))

Travel ../books/travel_2/index.html
Mystery ../books/mystery_3/index.html
Historical Fiction ../books/historical-fiction_4/index.html
Sequential Art ../books/sequential-art_5/index.html
Classics ../books/classics_6/index.html
Philosophy ../books/philosophy_7/index.html
Romance ../books/romance_8/index.html
Womens Fiction ../books/womens-fiction_9/index.html
Fiction ../books/fiction_10/index.html
Childrens ../books/childrens_11/index.html
Religion ../books/religion_12/index.html
Nonfiction ../books/nonfiction_13/index.html
Music ../books/music_14/index.html
Default ../books/default_15/index.html
Science Fiction ../books/science-fiction_16/index.html
Sports and Games ../books/sports-and-games_17/index.html
Add a comment ../books/add-a-comment_18/index.html
Fantasy ../books/fantasy_19/index.html
New Adult ../books/new-adult_20/index.html
Young Adult ../books/young-adult_21/index.html
Science ../books/science_22/index.html
Poetry ../books/poetry_23/index.html
Paranormal ../books/paranormal_24/index.html
Art ../books/art_25/index.html
Psychology ../books/psychology_26/index.html
Autobiography ../books/autobiography_27/index.html
Parenting ../books/parenting_28/index.html
Adult Fiction ../books/adult-fiction_29/index.html
Humor ../books/humor_30/index.html
Horror ../books/horror_31/index.html
History ../books/history_32/index.html
Food and Drink ../books/food-and-drink_33/index.html
Christian Fiction ../books/christian-fiction_34/index.html
Business ../books/business_35/index.html
Biography ../books/biography_36/index.html
Thriller ../books/thriller_37/index.html
Contemporary ../books/contemporary_38/index.html
Spirituality ../books/spirituality_39/index.html
Academic ../books/academic_40/index.html
Self Help ../books/self-help_41/index.html
Historical ../books/historical_42/index.html
Christian ../books/christian_43/index.html
Suspense ../books/suspense_44/index.html
Short Stories ../books/short-stories_45/index.html
Novels ../books/novels_46/index.html
Health ../books/health_47/index.html
Politics ../books/politics_48/index.html
Cultural ../books/cultural_49/index.html
Erotica ../books/erotica_50/index.html
Crime ../books/crime_51/index.html

In [46]:
#Create an empty list for all your data
all_books = []

In [50]:
for category_link in category_links:
    category=category_link.get_text(strip=True)
    category_href=category_link.get("href")
    category_url = urljoin(url, category_href)
    response=requests.get(category_url)
    category_soup=BeautifulSoup(response.text,"html.parser")
    books=category_soup.find_all("article", class_="product_pod")
    for book in books:
        title=book.h3.a.get("title")
        price=float(book.find("p",class_="price_color").get_text(strip=True).replace("£","").replace("Â",""))
        availability=book.find("p",class_="instock availability").get_text(strip=True)
        all_books.append({
            "Category":category,
            "Title":title,
            "Price":price,
            "Availability":availability
        })

In [51]:
df_page1=pd.DataFrame(all_books)
df_page1.head()

,Category,Title,Price,Availability
0,Travel,It's Only the Himalayas,45.17,In stock
1,Travel,Full Moon over Noahâs Ark: An Odyssey to Mou...,49.43,In stock
2,Travel,See America: A Celebration of Our National Par...,48.87,In stock
3,Travel,Vagabonding: An Uncommon Guide to the Art of L...,36.94,In stock
4,Travel,Under the Tuscan Sun,37.33,In stock

In [52]:
df_page1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      517 non-null    object
 1   Title         517 non-null    object
 2   Price         517 non-null    float64
 3   Availability  517 non-null    object
dtypes: float64(1), object(3)
memory usage: 16.3+ KB

In [55]:
# Find the nested <ul> containing the categories
category_list=side_categories.find("ul").find("ul")
# Find all category links
category_links=category_list.find_all("a")

In [69]:
all_books=[]
for category_link in category_links:

    category = category_link.get_text(strip=True)
    category_href = category_link.get("href")
    category_url = urljoin(url, category_href)

    current_url = category_url

    while current_url:

        print("Scraping:", current_url)

        response = requests.get(current_url, timeout=10)

        category_soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        books = category_soup.find_all(
            "article",
            class_="product_pod"
        )

        for book in books:

            title = book.h3.a.get("title")

            price = float(
                book.find(
                    "p",
                    class_="price_color"
                )
                .get_text(strip=True)
                .replace("£", "")
                .replace("Â", "")
            )

            availability = book.find(
                "p",
                class_="instock availability"
            ).get_text(strip=True)

            all_books.append({
                "Category": category,
                "Title": title,
                "Price": price,
                "Availability": availability
            })

        # Look for the "next" button
        next_link = category_soup.find(
            "li",
            class_="next"
        )

        if next_link:

            next_href = next_link.a.get("href")

            current_url = urljoin(
                current_url,
                next_href
            )

        else:

            current_url = None

Scraping: https://books.toscrape.com/catalogue/category/books/travel_2/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/mystery_3/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/mystery_3/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/historical-fiction_4/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/historical-fiction_4/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/sequential-art_5/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/sequential-art_5/page-3.html
Scraping: https://books.toscrape.com/catalogue/category/books/sequential-art_5/page-4.html
Scraping: https://books.toscrape.com/catalogue/category/books/classics_6/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/philosophy_7/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/romance_8/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/romance_8/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/womens-fiction_9/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/fiction_10/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/fiction_10/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/fiction_10/page-3.html
Scraping: https://books.toscrape.com/catalogue/category/books/fiction_10/page-4.html
Scraping: https://books.toscrape.com/catalogue/category/books/childrens_11/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/childrens_11/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/religion_12/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/nonfiction_13/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/nonfiction_13/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/nonfiction_13/page-3.html
Scraping: https://books.toscrape.com/catalogue/category/books/nonfiction_13/page-4.html
Scraping: https://books.toscrape.com/catalogue/category/books/nonfiction_13/page-5.html
Scraping: https://books.toscrape.com/catalogue/category/books/nonfiction_13/page-6.html
Scraping: https://books.toscrape.com/catalogue/category/books/music_14/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/default_15/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/default_15/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/default_15/page-3.html
Scraping: https://books.toscrape.com/catalogue/category/books/default_15/page-4.html
Scraping: https://books.toscrape.com/catalogue/category/books/default_15/page-5.html
Scraping: https://books.toscrape.com/catalogue/category/books/default_15/page-6.html
Scraping: https://books.toscrape.com/catalogue/category/books/default_15/page-7.html
Scraping: https://books.toscrape.com/catalogue/category/books/default_15/page-8.html
Scraping: https://books.toscrape.com/catalogue/category/books/science-fiction_16/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/sports-and-games_17/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/add-a-comment_18/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/add-a-comment_18/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/add-a-comment_18/page-3.html
Scraping: https://books.toscrape.com/catalogue/category/books/add-a-comment_18/page-4.html
Scraping: https://books.toscrape.com/catalogue/category/books/fantasy_19/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/fantasy_19/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/fantasy_19/page-3.html
Scraping: https://books.toscrape.com/catalogue/category/books/new-adult_20/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/young-adult_21/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/young-adult_21/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/young-adult_21/page-3.html
Scraping: https://books.toscrape.com/catalogue/category/books/science_22/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/poetry_23/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/paranormal_24/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/art_25/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/psychology_26/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/autobiography_27/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/parenting_28/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/adult-fiction_29/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/humor_30/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/horror_31/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/history_32/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/food-and-drink_33/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/food-and-drink_33/page-2.html
Scraping: https://books.toscrape.com/catalogue/category/books/christian-fiction_34/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/business_35/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/biography_36/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/thriller_37/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/contemporary_38/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/spirituality_39/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/academic_40/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/self-help_41/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/historical_42/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/christian_43/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/suspense_44/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/short-stories_45/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/novels_46/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/health_47/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/politics_48/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/cultural_49/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/erotica_50/index.html
Scraping: https://books.toscrape.com/catalogue/category/books/crime_51/index.html

In [70]:
books_df = pd.DataFrame(all_books)

books_df.shape

(1000, 4)

In [72]:
books_df.head(50)

,Category,Title,Price,Availability
0,Travel,It's Only the Himalayas,45.17,In stock
1,Travel,Full Moon over Noahâs Ark: An Odyssey to Mou...,49.43,In stock
2,Travel,See America: A Celebration of Our National Par...,48.87,In stock
3,Travel,Vagabonding: An Uncommon Guide to the Art of L...,36.94,In stock
4,Travel,Under the Tuscan Sun,37.33,In stock
5,Travel,A Summer In Europe,44.34,In stock
6,Travel,The Great Railway Bazaar,30.54,In stock
7,Travel,A Year in Provence (Provence #1),56.88,In stock
8,Travel,The Road to Little Dribbling: Adventures of an...,23.21,In stock
9,Travel,Neither Here nor There: Travels in Europe,38.95,In stock
10,Travel,"1,000 Places to See Before You Die",26.08,In stock
11,Mystery,Sharp Objects,47.82,In stock
12,Mystery,"In a Dark, Dark Wood",19.63,In stock
13,Mystery,The Past Never Ends,56.50,In stock
14,Mystery,A Murder in Time,16.64,In stock
15,Mystery,The Murder of Roger Ackroyd (Hercule Poirot #4),44.10,In stock
16,Mystery,The Last Mile (Amos Decker #2),54.21,In stock
17,Mystery,That Darkness (Gardiner and Renner #1),13.92,In stock
18,Mystery,Tastes Like Fear (DI Marnie Rome #3),10.69,In stock
19,Mystery,A Time of Torment (Charlie Parker #14),48.35,In stock
20,Mystery,A Study in Scarlet (Sherlock Holmes #1),16.73,In stock
21,Mystery,Poisonous (Max Revere Novels #3),26.80,In stock
22,Mystery,Murder at the 42nd Street Library (Raymond Amb...,54.36,In stock
23,Mystery,Most Wanted,35.28,In stock
24,Mystery,Hide Away (Eve Duncan #20),11.84,In stock
25,Mystery,Boar Island (Anna Pigeon #19),59.48,In stock
26,Mystery,The Widow,27.26,In stock
27,Mystery,Playing with Fire,13.71,In stock
28,Mystery,What Happened on Beale Street (Secrets of the ...,25.37,In stock
29,Mystery,The Bachelor Girl's Guide to Murder (Herringfo...,52.30,In stock
30,Mystery,Delivering the Truth (Quaker Midwife Mystery #1),20.89,In stock
31,Mystery,The Mysterious Affair at Styles (Hercule Poiro...,24.80,In stock
32,Mystery,In the Woods (Dublin Murder Squad #1),38.38,In stock
33,Mystery,The Silkworm (Cormoran Strike #2),23.05,In stock
34,Mystery,The Exiled,43.45,In stock
35,Mystery,The Cuckoo's Calling (Cormoran Strike #1),19.21,In stock
36,Mystery,Extreme Prey (Lucas Davenport #26),25.40,In stock
37,Mystery,Career of Evil (Cormoran Strike #3),24.72,In stock
38,Mystery,The No. 1 Ladies' Detective Agency (No. 1 Ladi...,57.70,In stock
39,Mystery,The Girl You Lost,12.29,In stock
40,Mystery,The Girl In The Ice (DCI Erika Foster #1),15.85,In stock
41,Mystery,Blood Defense (Samantha Brinkman #1),20.30,In stock
42,Mystery,1st to Die (Women's Murder Club #1),53.98,In stock
43,Historical Fiction,Tipping the Velvet,53.74,In stock
44,Historical Fiction,Forever and Forever: The Courtship of Henry Lo...,29.69,In stock
45,Historical Fiction,A Flight of Arrows (The Pathfinders #2),55.53,In stock
46,Historical Fiction,The House by the Lake,36.95,In stock
47,Historical Fiction,Mrs. Houdini,30.25,In stock
48,Historical Fiction,The Marriage of Opposites,28.08,In stock
49,Historical Fiction,Glory over Everything: Beyond The Kitchen House,45.84,In stock

In [74]:
books_df.columns

Index(['Category', 'Title', 'Price', 'Availability'], dtype='object')

In [76]:
books_df["Category"].nunique()

50

In [77]:
books_df["Category"].value_counts()

Category
Default               152
Nonfiction            110
Sequential Art         75
Add a comment          67
Fiction                65
Young Adult            54
Fantasy                48
Romance                35
Mystery                32
Food and Drink         30
Childrens              29
Historical Fiction     26
Poetry                 19
Classics               19
History                18
Womens Fiction         17
Horror                 17
Science Fiction        16
Science                14
Music                  13
Business               12
Travel                 11
Thriller               11
Philosophy             11
Humor                  10
Autobiography           9
Art                     8
Religion                7
Psychology              7
Spirituality            6
New Adult               6
Christian Fiction       6
Self Help               5
Sports and Games        5
Biography               5
Health                  4
Contemporary            3
Christian               3
Politics                3
Historical              2
Novels                  1
Cultural                1
Erotica                 1
Parenting               1
Academic                1
Short Stories           1
Suspense                1
Adult Fiction           1
Paranormal              1
Crime                   1
Name: count, dtype: int64